/*
 */
package pharmacyinventorymanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author Abdoullah Ndao
 */
public class SplashFrame extends javax.swing.JFrame {

    /**
     * Creates new form SplashFrame
     */
    public SplashFrame() {
        initComponents();
    }

    public void startApp() {
        this.setVisible(true);
        // Use SwingWorker to animate the progress bar off the EDT
        new javax.swing.SwingWorker<Void, Integer>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(25);
                    publish(i);
                }
                return null;
            }
            @Override
            protected void process(java.util.List<Integer> chunks) {
                int latest = chunks.get(chunks.size() - 1);
                progressBar.setValue(latest);
                percentage.setText(latest + "%");
            }
            @Override
            protected void done() {
                new LoginFrame().setVisible(true);
                dispose();
            }
        }.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        s_progress = new javax.swing.JPanel();
        closeX = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        title = new javax.swing.JLabel();
        mainIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        percentage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        s_progress.setBackground(new java.awt.Color(255, 255, 255));

        closeX.setBackground(new java.awt.Color(255, 255, 255));
        closeX.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        closeX.setForeground(new java.awt.Color(255, 51, 0));
        closeX.setText("x");
        closeX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeXMouseClicked(evt);
            }
        });

        progressBar.setBackground(new java.awt.Color(0, 204, 0));
        progressBar.setForeground(new java.awt.Color(0, 204, 51));
        progressBar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                progressBarPropertyChange(evt);
            }
        });

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(16, 185, 129));
        title.setText("PHARMACY INVENTORY MANAGEMENT SYSTEM");

        mainIcon.setText("+"); // Placeholder; original image path was Windows-specific

        jList1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Project by:", "Abdoullah Ndao" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        percentage.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        percentage.setForeground(new java.awt.Color(16, 185, 129));
        percentage.setText("100");
        percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout s_progressLayout = new javax.swing.GroupLayout(s_progress);
        s_progress.setLayout(s_progressLayout);
        s_progressLayout.setHorizontalGroup(
            s_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(s_progressLayout.createSequentialGroup()
                .addGroup(s_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, s_progressLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeX, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(s_progressLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(s_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(s_progressLayout.createSequentialGroup()
                                .addComponent(title)
                                .addGap(0, 80, Short.MAX_VALUE))
                            .addGroup(s_progressLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(s_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(s_progressLayout.createSequentialGroup()
                                        .addComponent(mainIcon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, s_progressLayout.createSequentialGroup()
                                        .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(128, 128, 128)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        s_progressLayout.setVerticalGroup(
            s_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(s_progressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeX)
                .addGap(2, 2, 2)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(s_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(s_progressLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(s_progressLayout.createSequentialGroup()
                        .addComponent(mainIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(s_progress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(s_progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void progressBarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_progressBarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_progressBarPropertyChange

    private void percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentageActionPerformed


    private void closeXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeXMouseClicked

        System.exit(0);
    }//GEN-LAST:event_closeXMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new SplashFrame().startApp());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeX;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainIcon;
    private javax.swing.JTextField percentage;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JPanel s_progress;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
